#
# Copyright (C) 2024 Antonino Scordino
# Copyright (C) 2024 Souhrud Reddy
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build in foss.crave.io
on:
  workflow_dispatch:
    inputs:
       BASE_PROJECT:
        description: 'Choose a base project:'
        required: true
        type: choice
        options:
          - 'AOSP'
          - 'LineageOS'
          - 'DerpFest'
          - 'PixelOS'
          - 'RisingOS'
       DEVICE_CODENAME:
        description: "Device codename:"
        required: true
        default: "apollo"
       BUILD_SCRIPT:
        description: 'Build script:'
        required: true
       BUILD_CLEAN:
        description: 'Build using a new/clean machine? (yes/no)'
        default: "no"

jobs:
  Start-Runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y tmux

      # Download and configure 'crave'.
    - name: Configure the 'crave' environment
      run: |
        mkdir ${HOME}/bin/
        curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
        mv ${PWD}/crave ${HOME}/bin/
        sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
        envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
        rm -rf ${PWD}/crave.conf.sample          

      env:
        CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
        CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}

    - name: Run crave devspace
      run: |
        crave devspace -- "
        echo "Looking for runner..."
          # Look for whether there's a runner folder set up
        if [ -f actions-runner/run.sh ] ; then
          echo -e '\e[32mRunner found! Restarting it...\e[0m'
        else
          echo -e '\e[31mError! Runner not found!\e[0m'
          exit 1
        fi

        if tmux has-session -t ghactions; then 
          echo -e '\e[32mRunner is already Running\e[0m'
        else 
          tmux kill-session -t ghactions;
          tmux new-session -d -s ghactions 
          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
          echo -e '\e[32mRunner Started\e[0m'
        fi "
        
  prepare:
    name: Prepare for Building
    runs-on: ubuntu-latest
    steps:
    - name: Check-out to repository
      uses: actions/checkout@v4

    - name: Check Credentials
      run: |
        if [[ -z "${{ secrets.CRAVE_TOKEN }}" || -z "${{ secrets.CRAVE_USERNAME }}" ]]; then
          echo -e '\e[31mCrave Credentials Not Configured! Exiting...\e[0m'
          exit 1
        fi
        bash configs/env-checker.sh

    - name: Set Project variables
      id: proj-variables
      run: |
        case "${{ github.event.inputs.BASE_PROJECT }}" in
          "AOSP") export PROJECTFOLDER="/crave-devspaces/AOSP"; export PROJECTID="35";;
          "DerpFest") export PROJECTFOLDER="/crave-devspaces/DerpFest-AOSP"; export PROJECTID="64";;
          "LineageOS") export PROJECTFOLDER="/crave-devspaces/LineageOS"; export PROJECTID="72";;
          "PixelOS") export PROJECTFOLDER="/crave-devspaces/PixelOS"; export PROJECTID="82";;
          "RisingOS") export PROJECTFOLDER="/crave-devspaces/RisingOS"; export PROJECTID="86";;
        esac
        
        echo "PROJECTFOLDER=$PROJECTFOLDER" >> $GITHUB_ENV
        echo "PROJECTID=$PROJECTID" >> $GITHUB_ENV
        
    outputs:
      PROJECTFOLDER: ${{ env.PROJECTFOLDER }}
      PROJECTID: ${{ env.PROJECTID }}
        
  build:
    needs: prepare
    timeout-minutes: 960
    name: Build in foss.crave.io
    runs-on: self-hosted
    
    steps:
    
    - name: Initialize build directory
      run: |
        PROJECTFOLDER="${{ needs.prepare.outputs.PROJECTFOLDER }}"
        PROJECTID="${{ needs.prepare.outputs.PROJECTID }}"
        
        existing_clones=$(crave clone list --json | jq -r '.clones[]."Cloned At"')
          
        for dir in $existing_clones; do
          if [[ "$dir" != "$PROJECTFOLDER" ]]; then
            echo "Removing old project directory: $dir"
            crave clone destroy -y "$dir"
          fi
        done

        # Check if the current project directory exists or create it
        if grep -q "$PROJECTFOLDER" <<< "$existing_clones" && [ "${DCDEVSPACE}" == "1" ]; then
          echo "Base project $PROJECTFOLDER build directory exists! Reusing it."
          echo "BUILD_DIR=$PROJECTFOLDER" >> $GITHUB_ENV
        else
          crave clone create --projectID "$PROJECTID" "$PROJECTFOLDER"
          echo "BUILD_DIR=$PROJECTFOLDER" >> $GITHUB_ENV
        fi

        echo "DEVICE_CODENAME=${{ github.event.inputs.DEVICE_CODENAME }}" >> $GITHUB_ENV
        echo "Building on $PROJECTFOLDER project"

    - name: Set up persistent hostname
      run: |
        cd ${{ env.BUILD_DIR }}
        
        if [ ! -f ".repo/manifests/crave.yaml" ]; then
            curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/configs/crave.yaml > .repo/manifests/crave.yaml
        fi

    - name: Clean compiled objects from previous build
      run: |
        cd ${{ env.BUILD_DIR }}

        rm -rf *.zip *sum *.img out

    - name: Queue build
      continue-on-error: true
      run: |
        cd ${{ env.BUILD_DIR }}

        jq '.projects = []' ~/crave.conf > tmp && mv tmp ~/crave.conf

        crave ssh -- "rm -f out/target/product/${{ env.DEVICE_CODENAME }}/*.zip out/target/product/${{ env.DEVICE_CODENAME }}/*sum"
        
        echo -e '\e[32mYour build is now on queue, check it on foss.crave.io\e[0m'
        [[ "${{ github.event.inputs.BUILD_CLEAN }}" == "yes" ]] && CLEAN_FLAG="--clean" || CLEAN_FLAG=""
        crave run $CLEAN_FLAG --no-patch -- "curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/scripts/${{ github.event.inputs.BUILD_SCRIPT }} | bash"

    - name: Error log
      continue-on-error: true
      run: |
        cd ${{ env.BUILD_DIR }}

        crave pull 'out/error.log'
        echo "Displaying error.log"
        cat out/error.log
        rm -rf out
        exit 0

    - name: Pulling compiled objects from build machine
      continue-on-error: false
      run: |
        cd ${{ env.BUILD_DIR }}

        NC='\033[0m'
        RED='\033[0;31m'

        crave pull 'out/target/product/${{ env.DEVICE_CODENAME }}/*.zip'
        rm -f *-ota-*.zip *-eng*.zip lineage*ota.zip aosp*ota.zip statix*ota.zip

        if [ -z "$(find . -maxdepth 1 -name '*.zip' | sed 's|^\./||')" ]; then
            echo -e '\e[31mERROR! The build might have failed, cancelled, or the runner died!\e[0m'
            echo -e '\e[31mCheck the error logs or go to foss.crave.io\e[0m'
            exit 1
        else
            crave pull 'out/target/product/${{ env.DEVICE_CODENAME }}/recovery*img' \
            'out/target/product/${{ env.DEVICE_CODENAME }}/*.sha256sum' \
            'out/target/product/${{ env.DEVICE_CODENAME }}/*.md5sum' \
            'out/target/product/${{ env.DEVICE_CODENAME }}/boot*img' \
            'out/target/product/${{ env.DEVICE_CODENAME }}/vendor_boot*img'

            mkdir -p out
            
            file_name=$(find . -maxdepth 1 -name '*.zip' | sed 's|^\./||')
            release_title=$(basename "$file_name" .zip)

            mv -f *.zip *.sha256sum *.md5sum *.img out/ || true
            
            echo "ZIP_FILE=$file_name" >> $GITHUB_ENV
            echo "RELEASE_DATE=$(date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV
            echo "RELEASENAME=$release_title" >> $GITHUB_ENV
        fi

    - name: Display files information
      run: |
        cd "${{ env.BUILD_DIR }}/out"

        echo "FILE PATH: ${{ env.BUILD_DIR }}/out"
        echo "File details:"
        find . -type f -exec ls -lh {} \; | awk '{print $9 ": " $5}'

    - name: Upload to GitHub releases
      run: |
        cd ${{ env.BUILD_DIR }}

        NC='\033[0m'
        RED='\033[0;31m'

        if ! command -v gh &> /dev/null; then
           echo "gh could not be found. Installing gh..."
           curl -sS https://webi.sh/gh | sh
           source ~/.config/envman/PATH.env
           echo "gh installed."
        fi

        gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

        if [[ -f "${{ env.BUILD_DIR }}/out/${{ env.ZIP_FILE }}" ]]; then
           file_size=$(stat -c%s "${{ env.BUILD_DIR }}/out/${{ env.ZIP_FILE }}")
           if [[ $file_size -le 2147483648 ]]; then
              gh release create ${{ github.run_id }} --repo ${{ github.repository }} --title ${{ env.RELEASENAME }} --notes "Released on ${{ env.RELEASE_DATE }}"
              gh release upload ${{ github.run_id }} --repo ${{ github.repository }} ${{ env.BUILD_DIR }}/out/*
           else
            echo -e '\e[31mERROR! ROM zip file is too large for GitHub release!\e[0m'
            echo -e '\e[31mGo to your devspace and upload it somewhere else!\e[0m'
           fi
        fi

    - name: Execute if the job is cancelled
      if:  ${{ cancelled() }}
      run: |
        cd ${{ env.BUILD_DIR }}

        crave stop --all

