#
# Copyright (C) 2024 Antonino Scordino
# Copyright (C) 2024 Souhrud Reddy
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build in Crave.io
on:
  workflow_dispatch:
    inputs:
       BASE_PROJECT:
        description: 'Choose a base project:'
        required: true
        type: choice
        options:
          - 'LineageOS 20.0'
          - 'LineageOS 21.0'
          - 'ArrowOS 13.1'
          - 'DerpFest 14.0'
          - 'CipherOS 14'
          - 'PixelOS 14'
          - 'RisingOS 14'
          - 'LineageOS 18.1'
          - 'LineageOS 16.0'
          - 'CyanogenMOD 14.1'
       DEVICE_CODENAME:
        description: "Device codename:"
        required: true
        default: "apollo"
       PROJECT:
        description: "What's the ROM? (only for Telegram notification)"
       BUILD_SCRIPT:
        description: 'Build script to use'
        required: true

env:
 chatId: ${{ secrets.TELEGRAM_TO }}
 botToken: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  Start-Runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      # Download and configure 'crave'.
    - name: Configure the 'crave' environment
      run: |
          mkdir ${HOME}/bin/
          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
          mv ${PWD}/crave ${HOME}/bin/
          sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
          envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
          rm -rf ${PWD}/crave.conf.sample
      env:
        CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
        CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}

    - name: Run crave devspace
      run: |
        crave -n devspace -- "if tmux has-session -t ghactions; then
          echo "Runner is already Running"
        else
          tmux kill-session -t ghactions;
          tmux new-session -d -s ghactions
          tmux send-keys -t ghactions './actions-runner/run.sh' Enter
          echo "Runner Started"
        fi "

  build:
    timeout-minutes: 960
    name: Build using foss.crave.io
    runs-on: self-hosted
    
    steps:
    
      # Create a build dir
    - name: Set-up build dir
      run: |
        case "${{ github.event.inputs.BASE_PROJECT }}" in
        "ArrowOS 13.1")
          export PROJECTFOLDER="/crave-devspaces/Arrow13"
          export PROJECTID="73"
        ;;
        "DerpFest 14.0")
          export PROJECTFOLDER="/crave-devspaces/DerpFest14"
          export PROJECTID="64"
        ;;
        "LineageOS 21.0")
          export PROJECTFOLDER="/crave-devspaces/Lineage21"
          export PROJECTID="72"
        ;;
        "LineageOS 20.0")
          export PROJECTFOLDER="/crave-devspaces/Lineage20"
          export PROJECTID="36"
        ;;
        "CipherOS 14")
          export PROJECTFOLDER="/crave-devspaces/Cipher14"
          export PROJECTID="79"
        ;;
        "PixelOS 14")
          export PROJECTFOLDER="/crave-devspaces/Pixel14"
          export PROJECTID="82"
        ;;
        "RisingOS 14")
          export PROJECTFOLDER="/crave-devspaces/Rising14"
          export PROJECTID="86"
        ;;
        "LineageOS 18.1")
          export PROJECTFOLDER="/crave-devspaces/Lineage18"
          export PROJECTID="85"
        ;;
        "LineageOS 16.0")
          export PROJECTFOLDER="/crave-devspaces/Lineage16"
          export PROJECTID="81"
        ;;
        "CyanogenMOD 14.1")
          export PROJECTFOLDER="/crave-devspaces/Cyanogen14"
          export PROJECTID="83"
        ;;
        esac
        
          existing_clones=$(crave clone list --json | jq -r '.clones[]."Cloned At"')
          
          for dir in $existing_clones; do
            if [[ "$dir" != "$PROJECTFOLDER" ]]; then
              echo "Removing old project directory: $dir"
              crave clone destroy -y "$dir"
          fi
          done

          # Check if the current project directory exists or create it
          if grep -q "$PROJECTFOLDER" <<< "$existing_clones" && [ "${DCDEVSPACE}" == "1" ]; then
            echo "Base project $PROJECTFOLDER build directory exists! Reusing it."
            echo "BUILD_DIR=$PROJECTFOLDER" >> $GITHUB_ENV
          else
            crave clone create --projectID "$PROJECTID" "$PROJECTFOLDER"
            echo "BUILD_DIR=$PROJECTFOLDER" >> $GITHUB_ENV
          fi

        echo "DEVICE_CODENAME=${{ github.event.inputs.DEVICE_CODENAME }}" >> $GITHUB_ENV
        echo "ROM_NAME=${{ github.event.inputs.PROJECT }}" >> $GITHUB_ENV
        echo "Building on $PROJECTFOLDER project"

    - name: Set-up build script
      run: |
        cd ${{ env.BUILD_DIR }}
        
        if [ -f "build.sh" ]; then
           rm -f build.sh
        fi
        curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/scripts/${{ github.event.inputs.BUILD_SCRIPT }} > build.sh

        if [ ! -f ".repo/manifests/crave.yaml" ]; then
            curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/configs/crave.yaml > .repo/manifests/crave.yaml
        fi

    - name: Start compilation (Queue)
      continue-on-error: true
      run: |
        cd ${{ env.BUILD_DIR }}

        send_telegram_message() {
          local message="$1"
          curl -s -X POST \
          https://api.telegram.org/bot$botToken/sendMessage \
          -d chat_id=$chatId \
          -d text="$message" \
          -d parse_mode="Markdown" \
          -d disable_web_page_preview=true
        }

        send_telegram_message "Build for Project: ${{ env.ROM_NAME }}%0ADevice: ${{ env.DEVICE_CODENAME}}%0ASTATUS: Initiated%0ACheck Info at: %0Ahttps://github.com/$(echo "${{ github.repository }}" | sed 's@_@\\_@g')/actions/runs/${{ github.run_id }}"

        jq '.projects = []' ~/crave.conf > tmp && mv tmp ~/crave.conf

        crave ssh -- "rm -f out/target/product/${{ env.DEVICE_CODENAME }}/*.zip out/target/product/${{ env.DEVICE_CODENAME }}/*sum"
        
        bash build.sh

    - name: Error logs
      continue-on-error: true
      run: |
        cd ${{ env.BUILD_DIR }}

        crave pull 'out/error.log'
        echo "Displaying error.log"
        cat out/error.log
        rm -rf out
        exit 0

    - name: Preparing compiled objects
      continue-on-error: false
      run: |
        cd ${{ env.BUILD_DIR }}

        NC='\033[0m'
        RED='\033[0;31m'

        send_telegram_message() {
          local message="$1"
          curl -s -X POST \
          https://api.telegram.org/bot$botToken/sendMessage \
          -d chat_id=$chatId \
          -d text="$message" \
          -d parse_mode="Markdown" \
          -d disable_web_page_preview=true
        }

        rm -f *.zip
        rm -f *sum
        rm -rf out
        
        crave pull 'out/target/product/${{ env.DEVICE_CODENAME }}/*.zip'
        rm -f *ota*.zip
        if [ -z "$(find . -maxdepth 1 -name '*.zip' | sed 's|^\./||')" ]; then
            send_telegram_message "Build for Project: ${{ env.ROM_NAME }}%0ADevice: ${{ env.DEVICE_CODENAME}}%0ASTATUS: Failed or Cancelled%0ACheck Info at: %0Ahttps://github.com/$(echo "${{ github.repository }}" | sed 's@_@\\_@g')/actions/runs/${{ github.run_id }}"
            echo -e ${RED} "#######################################################################"
            echo -e ${RED} "##                    ROM ZIP FILE NOT FOUND!!!                      ##"
            echo -e ${RED} "##     THE BUILD MIGHT'VE FAILED, CANCELLED OR THE RUNNER DIED.      ##"
            echo -e ${RED} "##            CHECK THE ERROR LOG OR GO TO FOSS.CRAVE.IO             ##"
            echo -e ${RED} "#######################################################################${NC}"
            exit 1
        else
            crave pull 'out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/recovery.img' \
            'out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/*sum' \
            'out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/${{ github.event.inputs.DEVICE_CODENAME }}.json' \
            'out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/boot.img' \
            'out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/${{ github.event.inputs.DEVICE_CODENAME }}_changelog.txt'
        
            file_name=$(find . -maxdepth 1 -name '*.zip' ! -name '*ota*' -print | sed 's|^\./||')
            release_title=$(basename "$file_name" .zip)

            echo "ZIP_FILE=$file_name" >> $GITHUB_ENV
            echo "RELEASE_DATE=$(date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV
            echo "RELEASENAME=$release_title" >> $GITHUB_ENV
        fi

    - name: Upload to GitHub releases
      run: |
        cd ${{ env.BUILD_DIR }}

        NC='\033[0m'
        RED='\033[0;31m'

        send_telegram_message() {
          local message="$1"
          curl -s -X POST \
          https://api.telegram.org/bot$botToken/sendMessage \
          -d chat_id=$chatId \
          -d text="$message" \
          -d disable_web_page_preview=true
        }

        gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

        if [[ -f "${{ env.ZIP_FILE }}" ]]; then
           file_size=$(stat -c%s "${{ env.ZIP_FILE }}")
           if [[ $file_size -le 2147483648 ]]; then
              gh release create ${{ github.run_id }} --repo ${{ github.repository }} --title ${{ env.RELEASENAME }} --notes "Released on ${{ env.RELEASE_DATE }}"
              gh release upload ${{ github.run_id }} --repo ${{ github.repository }} ${{ env.ZIP_FILE }} *sum out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/*
              send_telegram_message "Build for Project: ${{ env.ROM_NAME }}%0ADevice: ${{ env.DEVICE_CODENAME }}%0ASTATUS: Done! Uploaded to GitHub release%0ADownload at: https://github.com/${{ github.repository }}/releases/tag/${{ github.run_id }}"
           else
              send_telegram_message "${{ env.ZIP_FILE }} is too large!!! Cannot be uploaded to GitHub release. You can manually upload it from devspace%0AFILE PATH: ${{ env.BUILD_DIR }}/${{ env.ZIP_FILE }}"
              echo -e ${RED} "#######################################################################"
              echo -e ${RED} "##          ROM ZIP FILE IS TOO LARGE FOR GITHUB RELEASE!!           ##"
              echo -e ${RED} "##         GO TO YOUR DEVSPACE AND UPLOAD IT SOMEWHERE ELSE          ##"
              echo -e ${RED} "#######################################################################${NC}"
              echo "FILE PATH: ${{ env.BUILD_DIR }}/${{ env.ZIP_FILE }}"
           fi
        fi

    - name: Execute if the job is cancelled
      if:  ${{ cancelled() }}
      run: |
        cd ${{ env.BUILD_DIR }}

          send_telegram_message() {
          local message="$1"
          curl -s -X POST \
          https://api.telegram.org/bot$botToken/sendMessage \
          -d chat_id=$chatId \
          -d text="$message"
        }
        
        crave stop --all

        send_telegram_message "Build for Project: ${{ env.ROM_NAME }}%0ADevice: ${{ env.DEVICE_CODENAME }}%0ASTATUS: Cancelled%0ACheck Info at: %0Ahttps://github.com/$(echo "${{ github.repository }}" | sed 's@_@\\_@g')/actions/runs/${{ github.run_id }}"
