#
# Copyright (C) 2024 Antonino Scordino
# Copyright (C) 2024 Souhrud Reddy
#
# SPDX-License-Identifier: Apache-2.0
#

name: Gdrive Upload
on:
  workflow_dispatch:

jobs:
  Start-Runner:
    uses: ./.github/workflows/start-runner.yml
    secrets: inherit

  upload:
    timeout-minutes: 960
    name: Prepare zip from devspace
    runs-on: self-hosted
    
    steps:
    
    - name: Initialize build directory
      run: |
        build_dir=$(crave clone list --json | jq -r '.clones[]."Cloned At"')
        echo "BUILD_DIR=$build_dir" >> $GITHUB_ENV

    - name: Preparing ROM zip
      continue-on-error: false
      run: |
        cd ${{ env.BUILD_DIR }}/out

        file_name=$(find . -maxdepth 1 -name '*.zip' | sed 's|^\./||')
        echo $file_name
        bash_upload=$(curl -s -F "file=@$file_name" bashupload.com)
        download_link=$(echo "$bash_upload" | grep -o 'wget .*' | sed 's/^wget //')
        echo $download_link
        
        echo "DOWNLOAD_LINK=$download_link" >> $GITHUB_ENV
        echo "FILE_NAME=$file_name" >> $GITHUB_ENV

    outputs:
      DOWNLOAD_LINK: ${{ env.DOWNLOAD_LINK }}
      FILE_NAME: ${{ env.FILE_NAME }}
      
  upload-to-gdrive:
    needs: upload
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:

      - name: Download the zip
        run: |
          DOWNLOAD_LINK="${{ needs.upload.outputs.DOWNLOAD_LINK }}"
          FILE_NAME="${{ needs.upload.outputs.FILE_NAME }}"
          rm -rf ${{ github.workspace }}/*
          wget $DOWNLOAD_LINK

          ROM_ZIP=$(ls -- *.zip)

          if [ "$ROM_ZIP" != "$FILE_NAME" ]; then
             mv "$ROM_ZIP" "$FILE_NAME"
          fi

          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
       
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GSERVICE }}
          folderId: ${{ secrets.FOLDER_ID }}
          filename: ${{ env.FILE_NAME }}
          overwrite: "true"
 
